Dan cta bus
chicagonow/test-repository pull request #25
Opened 2018-03-12 04:26 UTC by dan8239

Hey guys, tested the CTA Bus near me user story via dummy JSON file inputting route 20 and Eastbound. Note that it doesn't work with the 135, but that's due to the CTA app not having any stop predictions for that route. It throws a "none scheduled" error. We'll have to error protect that.

Also note that I added slots to the intent, to account for us needing to specify a direction when calling the bus API.

I have a funeral to attend tomorrow so I cannot meet. Please pull this in without me if at all possible.

2018-03-13 00:31 UTC, baumannalexj requested changes
we'll clean up the console outs and making constants

2018-03-13 00:31 UTC, baumannalexj commented on .ask/config
> +      "skill_id": "amzn1.ask.skill.68bc5ea2-f393-4596-a0d8-64f9e1790a09",
reminder to revert

2018-03-13 00:31 UTC, baumannalexj commented on .ask/config
> +                "uri": "chicago-now-dan"
reminder to revert

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/helpers/DistanceCalculator.js
> +    if (unit=="K") { dist = dist * 1.609344; }
we can use "switch"  and make the units a const/enum in DistanceCalculator

2018-03-13 00:31 UTC, baumannalexj commented on skill.json
> +          "name": "ChicagoNow-dan"
reminder to revert

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/helpers/UTCTimeToEnglish.js
> +    let  ctaObject = {
I'll rename these

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/handlers/transit/bus/BusHandler.js
> +    console.log("Entered BusHandler.getBusesForRouteAndStop");
reminder

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/handlers/transit/bus/BusHandler.js
> +    console.log(url);
reminder

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/handlers/transit/bus/BusHandler.js
> +        console.log("entered request method");
reminder

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/handlers/transit/bus/BusHandler.js
> +        console.log("latitude: " + location.latitude);
reminder

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/repositories/transit/CtaBusRepository.js
> +    console.log("Entered GetNearestStopID Function:");
reminder

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/repositories/transit/CtaBusRepository.js
> +    console.log(url);
reminder

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/repositories/transit/CtaBusRepository.js
> +        console.log("CTABusRepository.getNearestStopId()");
reminder

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/repositories/transit/CtaBusRepository.js
> +    console.log("Entered CtaBusRepository.closestStopID()");
reminder

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/repositories/transit/CtaBusRepository.js
> +        console.log("Distance to stop " + thisStopId + ": " + thisDistance);
reminder

2018-03-13 00:31 UTC, baumannalexj commented on lambda/custom/repositories/transit/CtaBusRepository.js
> +    console.log("Closest StopID: " + closestStopId);
remidner

2018-03-13 00:31 UTC, baumannalexj commented on intent-service/skill.json
> +          "name": "ChicagoNow-dan"
I think this file is errant

2018-03-14 03:16 UTC, rknruben56 commented on lambda/custom/index.js
> +            BusHandler.searchBusNearMe(parameters, (alexaResponse) => {
shouldn't need BusHandler in index.js since TransitHandler has the method but we can always change it later if needed.

2018-03-14 03:16 UTC, rknruben56 approved these changes

2018-04-08 20:29 UTC, closed without merging