Refactored EventsNearMe to use async/await
chicagonow/test-repository pull request #35
Opened 2018-03-29 01:46 UTC by dan8239

2018-03-30 16:31 UTC, rknruben56 requested changes
Awesome job guys. Can't believe this actually works. I would just clean it up and then it's ready to merge

2018-03-30 16:31 UTC, rknruben56 commented on lambda/custom/controllers/IntentController.js
> +exports.getEventsWithUserLocation = async function getEventsWithUserLocation(apiEndpoint, token, deviceID){
Should have a comment

2018-03-30 16:31 UTC, rknruben56 commented on lambda/custom/handlers/events/EventsHandler.js
> +exports.asyncGetEventsNearUserLocation = async function asyncGetEventsNearUserLocation(latitude, longitude){
should have the "async" prefix removed and have a comment. searchEventsNearMe() function on line 12 can now be removed too

2018-03-30 16:31 UTC, rknruben56 commented on lambda/custom/handlers/location/LocationHandler.js
> +exports.asyncGetLocation = async function asyncGetLocation(apiEndpoint, token, deviceId){
should have a comment

2018-03-30 16:31 UTC, rknruben56 commented on lambda/custom/index.js
> +        /*
commented out code can now be removed

2018-03-30 16:31 UTC, rknruben56 commented on lambda/custom/test/controllers/IntentControllerTest.js
> +    it('In: returns correct Alexa Response', async function(){
should have the function name you're testing

2018-03-30 16:31 UTC, rknruben56 commented on lambda/custom/test/handlers/events/EventsHandlerTest.js
> +
test on line 41 can now be removed

2018-03-31 19:27 UTC, baumannalexj commented
since some functions still use the non async functions, maybe we leave them until all the refactoring is done, release
then remove the unused code

2018-03-31 19:28 UTC, baumannalexj approved these changes

2018-03-31 19:28 UTC, merged